# Generated by Django 3.2.20 on 2023-09-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
