# Generated by Django 3.2.20 on 2023-09-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0003_alter_wish_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='image',
        ),
    ]
